export const INITIALIZE_TODO_STATE = "INITIALIZE_TODO_STATE";
export const ADD_TODO = "ADD_TODO";
export const TOGGLE_TODO = "TOGGLE_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const SHOW_COMPLETED_TODO = "SHOW_COMPLETED_TODO";
export const SHOW_NOT_COMPLETED_TODO = "SHOW_NOT_COMPLETED_TODO";
export const SHOW_ALL_TODO = "SHOW_ALL_TODO";
